Remove js dir and update hooks

diff --git a/hooks/post-merge b/hooks/post-merge
--- a/hooks/post-merge
+++ b/hooks/post-merge
@@ -1,7 +1,15 @@
 #!/usr/bin/bash
 
 ../../php/php.exe wp-cli.phar post delete $(wp post list --post_type='post' --format=ids) --force
+
+if [ $? != 0 ]; then
+  echo "Could not commit, Xampp is not running!"
+  exit 1
+fi
+
 ../../php/php.exe wp-cli.phar post delete $(wp post list --post_type='page' --format=ids) --force
 ../../php/php.exe wp-cli.phar post delete $(wp post list --post_type='wp_global_styles' --for mat=ids) --force
 ../../php/php.exe wp-cli.phar plugin activate wordpress-importer
 ../../php/php.exe wp-cli.phar import export --authors=create
+
+exit 0
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -4,4 +4,11 @@ rm export/* -f
 
 ../../php/php.exe wp-cli.phar export --dir=export
 
+if [ $? != 0 ]; then
+  echo "Could not commit, Xampp is not running!"
+  exit 1
+fi
+
 git add export
+
+exit 0
